### PR TITLE
Implemented trading items

### PR DESCRIPTION
**Pull request by XavierDeFawks**
Implemented trading items

### CODE REVIEW

**Comment by XavierDeFawks** [comment]
It is a result. How do I pass as a nullable reference then lol

**Comment by Xijezu** [comment]
Honestly, I don't even know what you're trying to do with it. 
```cpp
if (!GiveItem(tradeTarget, it.first, it.second, nullptr))
```
You're passing the nullptr, change the value later on and it'll never get used outside the scope.
```cpp
    if(target_item != nullptr)
    {
        if(ResultItemHandle != nullptr)
            *ResultItemHandle = target_item->GetHandle();

        if(target_item != item)
            Item::PendFreeItem(item);
}
```
Not even mentioning that it doesn't get used in the scope as well.  
After this it just returns.  
I think you're misunderstanding the pseudocode in this case, it seems like this variable is/was used for logging purpose which is, in our case, useless.  
I haven't seen anything else related to that variable or parameter, so removing it should be fine.

**Comment by XavierDeFawks** [comment]
Fair enough. lol
I will go ahead and remove it.

**Comment by Xijezu** [comment]
```diff
+    for (auto &it : m_vTradeItemList)
+    {
+        if (!GiveItem(tradeTarget, it.first, it.second, nullptr))
+        {
+            return TS_RESULT_ACCESS_DENIED;
+        }
+    }
``` 
You forgot to remove the nullptr here. I'm going to pull it anyway and fix that issue real quick.
Make sure to actually test your code before pushing

**Pull request merged**
